[package]
name = "matrix-web-dto"
version = "0.1.0"
authors = ["James Meyer <jamesjmeyer210@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-web-entity = { path = "../matrix-web-entity" }