[package]
name = "matrix-web-api"
version = "0.1.0"
authors = ["james.meyer"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix-http-client = { path = "../matrix-http-client" }
actix-web = { version = "3", features = ["openssl"] }
actix-rt = "1"
serde = "1"
serde_json = "1"
openssl = "*"
urlencoding = "2.1.0"